server.port=${PORT:8080}
server.address=0.0.0.0

spring.application.name=myspace-backend
spring.main.web-application-type=reactive
spring.webflux.base-path=/

logging.level.reactor.netty=INFO
spring.webflux.multipart.max-in-memory-size=2MB