# application.properties
server.port=8080

spring.application.name=tech-news-app
news.api.key=pub_9c114068d5204b62b63f7f0e2087bd59

# Force WebFlux only (no WebMVC)
spring.main.web-application-type=reactive
spring.main.allow-bean-definition-overriding=false

# Logging
logging.level.com.technews.app=DEBUG
logging.level.reactor.netty=INFO

# WebFlux
spring.webflux.multipart.max-in-memory-size=2MB

